### ISSUE TITLE
C-CDA 2.1 issue - one OID for two different value sets

### ISSUE THREAD

**Issue by wendywise** [lantanagroup/trifolia#8] opened 2016-10-21 19:36 UTC
C-CDA 2.1 has introduced an issue where they are using one OID for two different value sets
One is SNOMED and one is LOINC.
Both need to be exported in the IG and voc.xml
Each are used in different constraints.
If a change is needed to an IG that is based on C-CDA 2.1, a user has to manually make the change.

TRIF-1102

**Comment by seanmcilvenna** [comment] 2016-10-25 15:15
@rgeimer, can you weigh in on this? This does _not_ seem right to me... I think two value sets being represented by one OID goes against some core terminology principles, and probably needs to be changed so that each value set has a different/unique OID.

**Comment by seanmcilvenna** [comment] 2016-12-08 20:54
#22 is a duplicate of this one.
There is more information in #22 though, so going to leave that one open and close this one.

**Closed by seanmcilvenna** 2016-12-08 20:54 UTC
Labels: enhancement
