### ISSUE TITLE
Template Edit causes templateId to change to be invalid

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#6] opened 2016-10-20 05:36 UTC
Trifolia is changing the long id in the template when I’m not even touching that field.  

I open the template to edit it.  I want to make a change to the name of the template and also the description. So I make the change to the Name.  I click somewhere else on the screen and check out what happens:

It goes from this:

![image](https://cloud.githubusercontent.com/assets/14354654/19547387/f5743610-96da-11e6-9ab3-d898decaf227.png)

To this:

![image](https://cloud.githubusercontent.com/assets/14354654/19547393/fd178638-96da-11e6-9fb2-a0572f75a600.png)

For some reason it decides to move the short id up into the extension part of the long id and it all becomes invalid.  I can’t even fix it easily because I no longer have the original oid and extension anywhere on the screen to fix it with.

**Comment by wendywise** [comment] 2016-10-21 19:58
TRIF-1116

**Comment by seanmcilvenna** [comment] 2016-11-11 01:41
This issue has been resolved as part of 4.2.1 which was deployed to production today. I am going to close this ticket out because you (Sarah/minigrrl) have already tested this in the development environment and confirmed that it is working.

**Closed by seanmcilvenna** 2016-11-11 01:41 UTC
Labels: bug, finished
