### ISSUE TITLE
C-CDA 2.1 has introduced an issue where they are using one OID for two different value sets

### ISSUE THREAD

**Issue by meenaxigosai** [lantanagroup/trifolia#19] opened 2016-11-10 00:28 UTC
C-CDA 2.1 has introduced an issue where they are using one OID for two different value sets
One is SNOMED and one is LOINC.    Both need to be exported in the IG and voc.xml
Each are used in different constraints.

Currently users are having to manually add stuff to the IG and will also have to manually fix the voc.xml file.

JIRA REFERENCE: TRIFSUP-510/TRIF-1102

**Comment by seanmcilvenna** [comment] 2016-12-08 20:51
This is a duplicate of #22.
Closing ticket and leaving #22 open.

**Closed by seanmcilvenna** 2016-12-08 20:51 UTC
Labels: duplicate
