### ISSUE TITLE
One oid, two code systems

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#22] opened 2016-11-12 01:58 UTC
See following screenshot.  Could we update the database so that EntityDeterminer references are replaced by HL7EntityDeterminer references. (and then deleting EntityDeterminer code system).

![image](https://cloud.githubusercontent.com/assets/14354654/20234877/4bad8968-a8cf-11e6-8ae2-8a740c157967.png)

**Comment by minigrrl** [comment] 2016-11-12 02:16
Same with these two (would like to kill HL7 Administrative Gender and replace it with HL7AdministrativeGender) I tried to find the members in value sets seeing as there are only 2, but coudln't find them:

![image](https://cloud.githubusercontent.com/assets/14354654/20234975/c4b6737c-a8d1-11e6-9856-0f9616aaf501.png)

**Comment by minigrrl** [comment] 2016-11-12 02:22
Same with these three (keep HL7ObservationInterpretation):

![image](https://cloud.githubusercontent.com/assets/14354654/20235007/a2494d18-a8d2-11e6-9683-a80b06a5003c.png)

**Comment by meenaxigosai** [comment] 2017-02-10 15:17
Confirmed this issue appears in the current build.  Created TRIF-1160.

**Comment by meenaxigosai** [comment] 2019-02-08 14:43
Hello @minigrrl ,

The fix for this issue (TRIF-1160) was released to production on November 7th, 2018, and as such, I will close out the GITHUB ticket.  If you feel the issue is not resolved, or have any other concerns, please open a ticket in the JIRA Support Desk.  

Best Regards,

Meenaxi Gosai

**Closed by meenaxigosai** 2019-02-08 14:43 UTC
Labels: enhancement
