### ISSUE TITLE
Not able to select value set

### ISSUE THREAD

**Issue by tcheng-altarum** [lantanagroup/trifolia#37] opened 2017-05-12 19:09 UTC
Value set selection dialog box just freeze, as a result NOT be able to bind to any value set. This references issue #35 that was closed but not fixed yet
[Doc1.pdf](https://github.com/lantanagroup/trifolia/files/997697/Doc1.pdf)

**Comment by meenaxigosai** [comment] 2017-05-12 20:43
Hello,

Thank you for providing the details of the value set used to bind to the template.  I have investigated further, and the OID urn:oid:2.16.840.1.113883.1.10 appears to be incorrect for the Birth Defects Diagnosis / Anamolies value set, and No Value Set Concepts are defined.  Please see attached screen shot.   I have opened JIRA ticket TRIF-1212 and will discuss with our engineering team.

Thank you for opening issue #37.   I am uncertain how Issue #35 was inadvertently closed and do apologize for the mishap.


Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST

**Comment by meenaxigosai** [comment] 2017-05-15 16:08
Hello,

Our engineering department has confirmed that this issue is related to the value set selection/identifier issue discovered late last week in Trifolia 4.0.    I have confirmed that in the Trifolia development environment (4.5) the issue is resolved. 

When a new version (4.5) of Trifolia is deployed to the production environment later on this week, you will be able to bind that new value set to the template.

Please let me know if you have any questions.

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST

**Comment by seanmcilvenna** [comment] 2017-05-18 21:14
Trifolia 4.5.0 has been released. This fix is included in the release. Please re-open the ticket if you encounter further problems related to this issue.

**Closed** 2017-05-18 21:14 UTC
Labels: bug, finished
