### ISSUE TITLE
auth0: "Last time you logged in using:"

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#2] opened 2016-10-05 01:08 UTC
In DEV.  (have cleared cache).  Login and get the auth0 message "Last time you logged in using:" .  Click on that user and it brings up: 
"Server Error
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable."

The url it is taking me to is: "http://dev.trifolia.lantanagroup.com/TemplateManagement/Edit/Id/6915,/TemplateManagement/Edit/Id/8130,/TemplateManagement/Edit/Id/7109,/TemplateManagement/Edit/Id/8145,/TemplateManagement/Edit/Id/7084,/TemplateManagement/List" 

which looks suspiciously like a bunch of templates I was editing earlier.

If I then go back to the regular Dev Trifolia link I'm logged in properly.  

So it's saving that url along with the login details somehow, I think.

(Even if I click "not my account" and re-enter the credentials it takes me to the same bad url).

Movie of behaviour here: http://screencast.com/t/YCOOyXkAf

**Comment by seanmcilvenna** [comment] 2016-10-07 20:19
Yah, there seems to be some occasional problem with how we tell OAuth to redirect to the intended location (ex: the template/profile editor) after successful authentication. If you can help figure out the chain of events that leads to this situation so I know how to consistently reproduce the problem, that would be helpful. Otherwise, I will pay attention for how this comes about when I *do* see it.

**Comment by minigrrl** [comment] 2016-10-07 23:16
Will try to reproduce in prod. It certainly hasn't happened to me in prod yet, but will play around with it next time I'm in there...

Sent from my iPad

On 8 Oct 2016, at 06:19, Sean McIlvenna <notifications@github.com<mailto:notifications@github.com>> wrote:


Yah, there seems to be some occasional problem with how we tell OAuth to redirect to the intended location (ex: the template/profile editor) after successful authentication. If you can help figure out the chain of events that leads to this situation so I know how to consistently reproduce the problem, that would be helpful. Otherwise, I will pay attention for how this comes about when I do see it.

-

**Comment by minigrrl** [comment] 2016-10-17 07:09
This just happened to me in production:
![image](https://cloud.githubusercontent.com/assets/14354654/19428256/6507e77a-948c-11e6-9640-119199b13f23.png)
Didn't do anything odd - just would have not used Trifolia for a couple of hours and left it on whatever screen I was last on...

**Comment by seanmcilvenna** [comment] 2016-10-18 16:20
This is an issue that has already been fixed in our development environments.
When we re-direct to auth0.com for authentication, we store some cookie information on where the user should be re-directed to _after_ they are done authenticating (ex: a specific implementation guide or template screen). What was happening, is that we were storing that cookie incorrectly, and instead ammending the cookie every time you authenticate, rather than setting the value entirely. Again, this has been addressed in our development environment. The fix will be included in the next release. I may bump up the next release date so that we get this fix out sooner, rather than later.

**Closed by seanmcilvenna** 2016-10-18 16:20 UTC
