### ISSUE TITLE
Can't edit an IG that I created

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#11] opened 2016-11-04 00:39 UTC
I created a second version of this IG: eICR CDA IG - C-CDA Templates Only (here: https://trifolia.lantanagroup.com/IGManagement/Edit/3284 )

I want to go and set the display name to something more meaningful so that I can show the IG to the client tomorrow.

I don't appear to have edit permissions (even though I have admin rights in Trifolia).  I have tried to add myself on the permissions screen, but even after I add myself, the "save" box is greyed out.  See below screenshots:
![image](https://cloud.githubusercontent.com/assets/14354654/19990635/d11e263a-a27a-11e6-9734-bf64c97dbfc0.png)

![image](https://cloud.githubusercontent.com/assets/14354654/19990444/9652b800-a279-11e6-8c11-7a6db9dd8b24.png)

I will have to manually edit the IG for now.

**Comment by seanmcilvenna** [comment] 2016-11-04 20:47
I think I know what the issue is here. We are checking for uniqueness of the identifier, but it is not taking into account the fact that this is a new version of the implementation guide, and although behind the scenes it is "technically" a different IG, to the end-user it represents something different. So, I will just have to have it ignore any identifiers that are previous versions of the ig when validating the uniqueness of the identifier.

**Comment by seanmcilvenna** [comment] 2016-11-04 20:59
Ok. After digging into this a bit I think we have a bigger problem. There are some implementation guides that are not versioned properly but use the same identifier. I'm not sure we will be able to force unique implementation guide identifiers given that. For now, I'm going to remove the unique identifier requirement on implementation guide so that it doesn't cause problems for end-users, but we should take a closer look at this in future calls.

**Comment by seanmcilvenna** [comment] 2016-11-04 21:11
Ok. I have removed the unique identifier validation logic (for now). I am updating the development environment with this change. @minigrrl, please test that this solves the problem you were originally having. If so, we can close this ticket out.

**Comment by minigrrl** [comment] 2016-11-07 07:55
I tried to test this but I had problems logging in and then when I was finally able to log in I couldn't version the iG (the loading... message came up).  Now it won't let me login at all.

**Comment by seanmcilvenna** [comment] 2016-11-11 01:36
This change has been applied to code (github) and deployed to https://trifolia.lantanagroup.com as part of 4.2.1

**Closed by seanmcilvenna** 2016-11-11 01:36 UTC
Labels: bug, finished
